language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
script:
  - npm i
  - npm install coveralls
  - npm run lint
  - npm test -- -u --coverage
after_success:
  - npm run coveralls
